- name: Create Gulpfile.js if non-existent
  template: src=Gulpfile.js dest={{ gulp_directory }}/Gulpfile.js force=no

- name: Create Gulp config file
  template: src=gulp.config.js dest={{ gulp_directory }}/gulp.config.js force=no
  when: gulp_create_config

- name: Create webpack.config.js
  template: src=webpack.config.js dest={{ gulp_directory }}/webpack.config.js force=no
  when: gulp_use_webpack

- name: Install Gulp globally
  npm: name=gulp global=yes
  become: yes

- name: Install PureScript globally
  npm: name=purescript global=yes
  become: yes
  when: gulp_use_purescript
